CREATE (KSALP:Kantonsschule {name:'KS Alpenquai', Abkuerzung:'KSALP'})
CREATE (KSBER:Kantonsschule {name:'KS Beromünster', Abkuerzung:'KSBER'})
CREATE (KSMUS:Kantonsschule {name:'KS Musegg', Abkuerzung:'KSMUS'})
CREATE (KSREU:Kantonsschule {name:'KS Reussbühl', Abkuerzung:'KSREU'})
CREATE (KSSEE:Kantonsschule {name:'KS Seetal', Abkuerzung:'KSSEE'})
CREATE (KSSCH:Kantonsschule {name:'KS Schüpfheim', Abkuerzung:'KSSCH'})
CREATE (KSSUR:Kantonsschule {name:'KS Sursee', Abkuerzung:'KSSUR'})
CREATE (KSWIL:Kantonsschule {name:'KS Willisau', Abkuerzung:'KSWIL'})
